### ISSUE TITLE
Barrio La Ceja repetido, ID 2344 y 2345 en la tabla localidades_postales

### ISSUE THREAD

**Issue by rcsoftinc** [raydelto/provincias_dominicanas#6]
Barrio La Ceja repetido, ID 2344 y 2345 en la tabla localidades_postales. Tambien en el nombre de la localidad de ID 983 de código postal 57202 (La Altagracia); Este mismi tipo de error se repite en el ID 1108 de código postal 71003 (Tambien Las Altagracia), me imagino que producto de alguna duda.

**Comment by raydelto** [comment]
Gracias @rcsoftinc por reportarlo ¿Pudieras por favor crear un pull request para arreglar este error?

**Comment by raydelto** [comment]
Gracias por reportarlo. Ya hemos arreglado el error.
